# Generated by Django 6.0.3 on 2026-04-09 00:54
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=13)),
                ('titulo', models.CharField(max_length=20)),
                ('publicacao', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estoque', models.IntegerField()),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.editora')),
            ],
        ),
        migrations.CreateModel(
            name='Publica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.autor')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.livro')),
            ],
        ),
    ]
