# Generated by Django 6.0.3 on 2026-04-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AddConstraint(
            model_name='publica',
            constraint=models.UniqueConstraint(fields=('livro', 'autor'), name='unique_livro_autor'),
        ),
    ]
