# Generated by Django 4.2.30 on 2026-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_alter_autor_nome_alter_editora_nome_alter_livro_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
